---
driver:
  name: docker

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  require_chef_for_busser: true

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:12.04
      socket: <%= ENV['DOCKER_HOST'] %>
      use_cache: true
      dockerfile: ubuntu12.04-dockerfile

suites:
  - name: webserver
    provisioner:
      manifest: site.pp
